### ISSUE TITLE
index.d.ts issue

### ISSUE THREAD

**Issue by HyunwooP** [HwangTaehyun/react-native-lottie-splash-screen#1]
typescript 

declare module "react-native-splash-screen" {
    export default class SplashScreen {
        static hide(): void;
        static show(): void;
    }
}

import is not module.. so, react-native-lottie-splash-screen self change and used
please confirm here

**Comment by HwangTaehyun** [comment]
I checked too late. Sorry. I'll add a type file as well.

**Comment by HwangTaehyun** [comment]
I add index.d.ts file for this project. Thank you!
