### ISSUE TITLE
[Android] RN  0.59.10 cannot build

### ISSUE THREAD

**Issue by LightKnight3r** [HwangTaehyun/react-native-lottie-splash-screen#10]
Run `react-native info` in your project and share the content.

What `react-native-splash-screen` version are you using?
0.1.14
What platform does your issue occur on? (Android/iOS/Both)
Android
Describe your issue as precisely as possible : 
  1) Steps to reproduce the issue or to explain in which case you get the issue
Android build errors: 
  2) Interesting `logs`
 Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:40:5-137:19 to override.
Join a screenshot or video of the problem on the simulator or device?

Show us the code you are using?

**Comment by girish54321** [comment]
Hi, @LightKnight3r have you tried manually installation steps.

**Comment by LightKnight3r** [comment]
@girish54321 yes, i have.
