### ISSUE TITLE
Build error iOS

### ISSUE THREAD

**Issue by snehsagarajput** [HwangTaehyun/react-native-lottie-splash-screen#13]
System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Memory: 735.16 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.1 - /opt/homebrew/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 7.20.5 - /opt/homebrew/bin/npm
    Watchman: 2021.08.02.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    
    
    
    
I am getting this error 

    
<img width="1428" alt="Screenshot 2021-08-24 at 1 00 50 AM" src="https://user-images.githubusercontent.com/39427821/130508307-3d27601b-cab7-4c6f-b3a4-2f754937386a.png">

**Comment by mayfairr** [comment]
How did you fix this?

**Comment by mayfairr** [comment]
If you get the error `Incompatible pointer types sending 'UIView *' to parameter of type 'AnimationView * _Nonnull'` or `Incompatible pointer types initializing 'UIView *' with an expression of type 'AnimationView *'`

please ensure that the AppDelegate is a Objective C file and **not** an Objective C++ file.  To change this, rename it from `AppDelegate.mm` to `AppDelegate.m`
