### ISSUE TITLE
Using this library on expo?

### ISSUE THREAD

**Issue by sykhan88** [HwangTaehyun/react-native-lottie-splash-screen#14]
Hi,
Any implementation of this package on expo? If yes, can you please share an example or provide starting info?

**Comment by sykhan88** [comment]
I did think of that and checked up youtube video. My only challenge with
that is how to show the splash screen when user has closed the app and
reopens it. I dont want to show the splash everytime appstate goes from
Background/inactive to active. React doesnt have a way of showing if the
the app was formally closed. If i ran compenent based on that logic, even
if the up goes into background, and then comes back up, the compoment will
run.
Am i correct on this? Any slick way around this?

**Comment by HwangTaehyun** [comment]
Sorry for my late reply! 
I don't have any examples for expo.. Sorry...

**Comment by HwangTaehyun** [comment]
@sykhan88 I applied this to the expo bare workflow and add some info to README.md!

**Comment by Noitidart** [comment]
Thanks very much. Expo these days has config plug-ins which allow for native. I haven't been able to successfully do this yet but just sharing in case a kind can https://docs.expo.dev/modules/config-plugin-and-native-module-tutorial/
