### ISSUE TITLE
Ablity to Change StatusBar and NavigationBar Color or Completely Hide them

### ISSUE THREAD

**Issue by aarizz** [HwangTaehyun/react-native-lottie-splash-screen#15]
First of All, Nice Work...

I was just curious if,  the StatusBar and Navigation bar color can be changed or hid completly while the Splash Screen is Loading.
The problem is I just wanted to set a solid color in the background of the Splash Screen, But found it ugly coz the status bar and bottom navigation bar is visible during the the animation.
I'am new to mobile development.
and will be a nice have if the package has this out of the box...

**Comment by Samwell1996** [comment]
Hey, you can change it if you add 
on func show a new param  "R.style.SplashScreenTheme"-  
SplashScreen.show(this, R.style.SplashScreenTheme,  R.id.lottie);

write your SplashScreenTheme - in res/values/styles.xml

thats should looks be - 
<style name="SplashScreenTheme" parent="SplashScreen_SplashTheme">
        <item name="android:statusBarColor">@color/yourColor</item>
        <item name="android:windowActionBar">false</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:navigationBarColor">@color/yourColor</item>
        < --- your different params --->>> 
    </style>

**Comment by Samwell1996** [comment]
@HwangTaehyun should you add this in new version?

**Comment by cryptic-dev** [comment]
> @HwangTaehyun should you add this in new version?

it would be great

**Comment by cryptic-dev** [comment]
> R.style.SplashScreenTheme

Thank you so much. I have very little java and android knowledge, you saved me.

**Comment by sobanarshad85** [comment]
how did you guys do iOS plugin configuration, step number 3 is not understandable they are opening a new link to read but yet ambiguous.

To use swift file in AppDelegate.m, follow next step.
https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_swift_into_objective-c

Import Swift code into Objective-C within the same framework:

Under Build Settings, in Packaging, make sure the Defines Module setting for that framework target is set to Yes.

Import the Swift code from that framework target into any Objective-C .m file within that target using this syntax and substituting the appropriate names:

**Comment by HwangTaehyun** [comment]
Hi! Sorry for my late reply.
@cryptic-dev @Samwell1996 @aarizz 
Below link is my answer to another issue!
https://github.com/HwangTaehyun/react-native-lottie-splash-screen/issues/6#:~:text=SplashScreen.show(this%2C%20R.style.SplashScreenTheme)%3B

I would add a more convenient way to change the background color and status bar color in lottie loading screen.
Thank you.

**Comment by AbhiSharma722** [comment]
Hi, I tried creating `SplashScreenTheme` theme and given as parameter to show function, but it didn't worked for me, I am using android 12 and it still showing status bar on splash screen

Can we have a fullscreen boolean parameter as other libraries are providing like show(fullscreen:boolean) something like this?
I can make PR for that
