### ISSUE TITLE
SplashScreen.show() => undefined is not a function

### ISSUE THREAD

**Issue by ChengZh98** [HwangTaehyun/react-native-lottie-splash-screen#16]
Hi, whenever i try to use the method SplashScreen.show( ) it says that the method is not been defined, any clue why is that? SplashScreen.hide() works just fine.

Thanks.

David.

**Comment by archcorsair** [comment]
I have the same problem with `hide()`
```js
import * as LottieSplashScreen from 'react-native-lottie-splash-screen';
```
![image](https://user-images.githubusercontent.com/1036921/138008433-4d168e59-b5d6-401e-a74c-2c4d983a9f42.png)

**Comment by HwangTaehyun** [comment]
Hi! I would check it out!

**Comment by HwangTaehyun** [comment]
I added the example project for android & ios (react-native: 0.69.1)
Then I checked it again, there was no issue!

**Comment by yuvrajchaudhari03** [comment]
@HwangTaehyun I'm facing the same issue. 
I have written code the same as the example project but still getting an error
```
TypeError: Cannot read property 'hide' of undefined

```
