### ISSUE TITLE
Conflicts with RNSplashscreen (iOS) build fail

### ISSUE THREAD

**Issue by sasha9878** [HwangTaehyun/react-native-lottie-splash-screen#17]
Run `react-native info` in your project and share the content.
System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz
    Memory: 58.25 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2021.10.11.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/user-name/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 

What `react-native-splash-screen` version are you using?
"react-native-splash-screen": "^3.1.1", 

What platform does your issue occur on? (Android/iOS/Both)
iOS(Didn't move to Android yet)

Describe your issue as precisely as possible : 
  1) Installed the package `yarn add react-native-lottie-splash-screen` , then `cd ios` and `pod install`. After that simply build the project `react-native run-ios` and got this error
  2) duplicate symbol '_OBJC_CLASS_$_RNSplashScreen' in:
    /Users/<user>/Library/Developer/Xcode/DerivedData/IdentityGuard-hfrixgiejpdpyecgibegosxauvyj/Build/Products/Debug-iphonesimulator/react-native-lottie-splash-screen/libreact-native-lottie-splash-screen.a(RNSplashScreen.o)
    /Users/<user>/Library/Developer/Xcode/DerivedData/IdentityGuard-hfrixgiejpdpyecgibegosxauvyj/Build/Products/Debug-iphonesimulator/react-native-splash-screen/libreact-native-splash-screen.a(RNSplashScreen.o)
duplicate symbol '_OBJC_METACLASS_$_RNSplashScreen' in:
    /Users/<user>/Library/Developer/Xcode/DerivedData/IdentityGuard-hfrixgiejpdpyecgibegosxauvyj/Build/Products/Debug-iphonesimulator/react-native-lottie-splash-screen/libreact-native-lottie-splash-screen.a(RNSplashScreen.o)
    /Users/<user>/Library/Developer/Xcode/DerivedData/IdentityGuard-hfrixgiejpdpyecgibegosxauvyj/Build/Products/Debug-iphonesimulator/react-native-splash-screen/libreact-native-splash-screen.a(RNSplashScreen.o)
ld: 2 duplicate symbols for architecture x86_64

More info-

- Already cleared Derived data.
- Clean and re-build project.

But still same issue. Not able to use this library even.

Join a screenshot or video of the problem on the simulator or device?
![Screenshot 2021-10-22 at 11 35 05 AM](https://user-images.githubusercontent.com/35032724/138401432-544adc2a-c7d5-4dbe-ae92-5d27e19b1e5d.png)
duplicate symbol '_OBJC_CLASS_$_RNSplashScreen' in:
duplicate symbol '_OBJC_METACLASS_$_RNSplashScreen' in:

**ALSO**
If I just follow the steps further I am getting these errors:
On `Dynamic.swift`
![Screenshot 2021-10-22 at 3 43 52 PM](https://user-images.githubusercontent.com/35032724/138437470-36837ab0-b75b-4834-a408-c7ffdd510140.png)

On `AppDelegate.m`
![Screenshot 2021-10-22 at 3 48 29 PM](https://user-images.githubusercontent.com/35032724/138437684-ea623792-d21a-4c1b-a908-3fa206b3afe3.png)

**Comment by girish54321** [comment]
I had same problem 
installing `lottie-react-native` will fix this.

**Comment by sasha9878** [comment]
installed `lottie-react-native` too, updated pods. Still no success.
Moreover getting very long wierd issue on terminal :- 
_long list of commands_ then 
** BUILD FAILED **
The following build commands failed:
        Ld /Users/sasha/Library/Developer/Xcode/DerivedData/IdentityGuard-hfrixgiejpdpyecgibegosxauvyj/Build/Products/Debug-iphonesimulator/DemoProject.app/DemoProject normal (in target 'DemoProject' from project 'DemoProject') 

Already cleared derived data.

**Comment by sasha9878** [comment]
installed lottie-react-native too, updated pods. Still no success.
Moreover getting very long wierd issue on terminal :-
long list of commands then
** BUILD FAILED **
The following build commands failed:
Ld /Users/sasha/Library/Developer/Xcode/DerivedData/IdentityGuard-hfrixgiejpdpyecgibegosxauvyj/Build/Products/Debug-iphonesimulator/DemoProject.app/DemoProject normal (in target 'DemoProject' from project 'DemoProject')

Already cleared derived data.

EDIT-1: Not a solution but restarting system made the Build successful on iOS.

How can I add background image and resize the animated view?
Do I need to open another issue ?

**Comment by sasha9878** [comment]
installed lottie-react-native too, updated pods. Still no success.
Moreover getting very long wierd issue on terminal :-
long list of commands then
** BUILD FAILED **
The following build commands failed:
Ld /Users/sasha/Library/Developer/Xcode/DerivedData/IdentityGuard-hfrixgiejpdpyecgibegosxauvyj/Build/Products/Debug-iphonesimulator/DemoProject.app/DemoProject normal (in target 'DemoProject' from project 'DemoProject')

Already cleared derived data.

EDIT-1: Not a solution but restarting system made the Build successful on iOS.
