### ISSUE TITLE
Cannot compile Android (Works on iOS)

### ISSUE THREAD

**Issue by archcorsair** [HwangTaehyun/react-native-lottie-splash-screen#18]
## What `react-native-splash-screen` version are you using?
`react-native-splash-screen`: not included as a direct dependency (Is this required?) it works on iOS without
Installed: `react-native-lottie-splash-screen: 0.1.14`

## What platform does your issue occur on? (Android/iOS/Both)
❌	Android does not work 
✅	iOS Works

### Error when compiling: in both Android Studio and RN-CLI
```
MainActivity.java:17: error: cannot find symbol
    SplashScreen.show(this, R.id.lottie);
                                ^
  symbol:   variable lottie
  location: class id
```

## Relevant Screenshots
![image](https://user-images.githubusercontent.com/1036921/139152017-68ff17bc-3b29-463d-8982-ea0e0eea3c45.png)
![image](https://user-images.githubusercontent.com/1036921/139152335-32c0309b-e3c4-41f8-afdf-a3a2cb5dcaab.png)

## Code Snippet
```java
// MainActivity.java
public class MainActivity extends ReactActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    SplashScreen.show(this, R.id.lottie);
    SplashScreen.setAnimationFinished(true);
    super.onCreate(savedInstanceState);
  }
```

## Run `react-native info` in your project and share the content.
```
Node: 16.9.1
Android Studio: 2020.3 AI-203.7717.56.2031.7784292
Xcode: 13.0/13A233
Java: 1.8.0_292
React Native: 0.64.2
```

**Comment by fbotalla** [comment]
Still having an issue after re-creating the `launch_scree.xml` file.. any other possible solutions? I also did try to do a manual import, but no luck.

**Comment by fbotalla** [comment]
@glushkina1 No, we ended up going a different route
