### ISSUE TITLE
Issue with Android node_modules class (Typecast error)

### ISSUE THREAD

**Issue by sasha9878** [HwangTaehyun/react-native-lottie-splash-screen#19]
Run `react-native info` in your project and share the content.
System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz
    Memory: 31.18 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: 2021.10.11.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /Users/sasha/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

What `react-native-splash-screen` version are you using?
"react-native-lottie-splash-screen": "^0.1.14"

What platform does your issue occur on? (Android/iOS/Both)
Android

Describe your issue as precisely as possible : 
```
  > Task :lottie-react-native:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
489 actionable tasks: 6 executed, 483 up-to-date
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
/Volumes/DATA/Project/DEMO/Projects/DEMO/IG/node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.java:168: error: incompatible types: LottieValueCallback<SimpleColorFilter> cannot be converted to LottieValueCallback<ColorFilter>
        LottieValueCallback<ColorFilter> callback = new LottieValueCallback<>(colorFilter);
                                                    ^
Note: /Volumes/DATA/Project/DEMO/Projects/DEMO/IG/node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
When building Android getting error from library file for types, however we can typecast it but doing it in node_modules is not preferred. Any solutions for this?
@HwangTaehyun 

Join a screenshot or video of the problem on the simulator or device?

Show us the code you are using? 
From library file, issue on line 168
![Screenshot 2021-11-22 at 9 17 30 PM](https://user-images.githubusercontent.com/35032724/142891930-2d8d068d-98bf-4a1b-bee8-15984726d519.png)

**Comment by HwangTaehyun** [comment]
Sorry for my late reply. I would check it!

**Comment by HwangTaehyun** [comment]
I added the example project for android & ios (react-native: 0.69.1)
Then I checked it again, there was no issue!
