### ISSUE TITLE
Getting Error in AppDelegate.m about the code mentioned in Plugin integration part. 

### ISSUE THREAD

**Issue by vishnau31** [HwangTaehyun/react-native-lottie-splash-screen#20]
Run `react-native info` in your project and share the content.

What `react-native-splash-screen` version are you using?

What platform does your issue occur on? (Android/iOS/Both)

Describe your issue as precisely as possible : 
  1) Steps to reproduce the issue or to explain in which case you get the issue
  2) Interesting `logs`

Join a screenshot or video of the problem on the simulator or device?

Show us the code you are using? 
![Screenshot 2021-11-25 at 12 58 12 AM](https://user-images.githubusercontent.com/34033476/143302333-e31e365f-cb70-40f3-b3e6-af5c9415946b.png)

**Comment by HwangTaehyun** [comment]
Sorry for my late reply. I would check it!

**Comment by M-b-v** [comment]
> Sorry for my late reply. I would check it!



> Run `react-native info` in your project and share the content.
> 
> What `react-native-splash-screen` version are you using?
> 
> What platform does your issue occur on? (Android/iOS/Both)
> 
> Describe your issue as precisely as possible :
> 
> 1. Steps to reproduce the issue or to explain in which case you get the issue
> 2. Interesting `logs`
> 
> Join a screenshot or video of the problem on the simulator or device?
> 
> Show us the code you are using? ![Screenshot 2021-11-25 at 12 58 12 AM](https://user-images.githubusercontent.com/34033476/143302333-e31e365f-cb70-40f3-b3e6-af5c9415946b.png)

u need to create the Dynamic swift file in xcode not vscode

**Comment by M-b-v** [comment]
> Sorry for my late reply. I would check it!

u need to create the Dynamic swift file in xcode not vscode
