### ISSUE TITLE
use of undeclared identifier 'Dynamic' [IOS]

### ISSUE THREAD

**Issue by sainyanhtay** [HwangTaehyun/react-native-lottie-splash-screen#22]
I already created Dynamic.Swift in the root of the ios folder. but when I try to build IOS, error shown like the following in the AppDelegate.m

`error: use of undeclared identifier 'Dynamic' in Dynamic *t = [Dynamic new];`

How can I solve, Thanks

**Comment by sainyanhtay** [comment]
it's solved by adding that file from Xcode. Thanks

**Comment by ariffathur** [comment]
hey @sainyanhtay can you provide where exactly the file should be put?

**Comment by sainyanhtay** [comment]
@ariffathur   you should open the project by Xcode and create a new file in that workspace. it will create one file in the ios folder of react native project.

**Comment by analaurafernandes** [comment]
I'm still having this issue... I created the Dynamic.swift and header files directly from xCode as you said... any other idea?

**Comment by HwangTaehyun** [comment]
Hi, Have you ever tried the following step?
https://github.com/HwangTaehyun/react-native-lottie-splash-screen#:~:text=To%20use%20swift,the%20appropriate%20names%3A

**Comment by analaurafernandes** [comment]
@HwangTaehyun Thanks for your answer! Curiously what solved my problem was to import "projectName-Swift.h" inside AppDelegate.h instead of inside AppDelegate.m... Now the splash screen is working very well :)

**Comment by HwangTaehyun** [comment]
@analaurafernandes Oh, I see! Good!!
