### ISSUE TITLE
Help with getting Lottie files into XCode

### ISSUE THREAD

**Issue by richardx0** [HwangTaehyun/react-native-lottie-splash-screen#24]
In your documentation it is mentioned in the Getting Started section for iOS:

> Drag your lottie files to Xcode Project. That's all. 

Can this be elaborated on? Where do you drop it? Is there a naming convention for the file? or are there more complex steps involved in getting this set up.

**Comment by richardx0** [comment]
I found in the comments of the code above this instruction just to name it `loading.json` (once you add the boilerplate code in the instructions)

**Comment by girish54321** [comment]
This will help @richardx0 [Link](https://github.com/HwangTaehyun/react-native-lottie-splash-screen/issues/4#issuecomment-808167134)
