### ISSUE TITLE
Please guide configuration step number 3, and when drag and drop file to Xcode where exactly to drop and do i have to rename json file that contains animation?

### ISSUE THREAD

**Issue by sobanarshad85** [HwangTaehyun/react-native-lottie-splash-screen#25]
Please guide configuration step number 3, and when drag and drop file to Xcode where exactly to drop and do i have to rename json file that contains animation?

**Comment by HwangTaehyun** [comment]
I guide lottie file name to **loading.json** in this project.
If you want to rename lottie file, then change below code location.
https://github.com/HwangTaehyun/react-native-lottie-splash-screen#:~:text=Dynamic%20*t%20%3D%20%5BDynamic%20new%5D%3B%0A%20%20UIView%20*animationView%20%3D%20%5Bt%20createAnimationViewWithRootView%3ArootView%20lottieName%3A%40%22loading%22%5D%3B%20//%20change%20lottieName%20to%20your%20lottie%20files%20name%0A%20%20animationView.backgroundColor%20%3D%20%5BUIColor%20whiteColor%5D%3B%20//%20change%20backgroundColor

Thank you.
