### ISSUE TITLE
How do I use lottie animation files? 

### ISSUE THREAD

**Issue by omniviewsports** [HwangTaehyun/react-native-lottie-splash-screen#26]
I am unsure how/where to place my lottie.json file. Please advise? Specifically, I used adobe after effects and generated the lottie file using the bodymovin plugin.

**Comment by girish54321** [comment]
Follow Docs or [this](https://github.com/HwangTaehyun/react-native-lottie-splash-screen/issues/4#issuecomment-803784619) 

You can get demo / example project [here](https://github.com/girish54321/SplashApp) (Not json file is messing in iOS)
