### ISSUE TITLE
AppDelegate.m

### ISSUE THREAD

**Issue by omniviewsports** [HwangTaehyun/react-native-lottie-splash-screen#27]
In the example app and the documentation one of the lines of code to add is as follow:

UIView *animationView = [t createAnimationViewWithRootView:rootView lottieName:@"loading"];

My project is called YourZone, so which of the following is correct?

A) UIView *animationView = [t createAnimationViewWithRootView:rootView lottieName:@"**YourZone**"];
B) UIView *animationView = [t createAnimationViewWithRootView:rootView **YourZone**:@"loading"];

**Comment by dazweeja** [comment]
It's not the project name, it's the asset name. So if your lottie animation was "circle.json", you would add this file to your project and then the code would be:

UIView *animationView = [t createAnimationViewWithRootView:rootView lottieName:@"circle"];
