### ISSUE TITLE
No such module "Lottie"

### ISSUE THREAD

**Issue by vitalykostak** [HwangTaehyun/react-native-lottie-splash-screen#28]
![screen_1](https://user-images.githubusercontent.com/46647764/156798764-73a571c0-e517-49df-9721-3c4659bc96a4.png)

![screen_2](https://user-images.githubusercontent.com/46647764/156793568-18bbcb65-2ad0-42e1-87b0-983b1509fb0b.png)

Hello. The problem is only on iOS on android everything is ok. What could I have done wrong?

**Comment by fbotalla** [comment]
What was the solution to this?

**Comment by girish54321** [comment]
@fbotalla  May be this will [Help](https://github.com/HwangTaehyun/react-native-lottie-splash-screen/issues/4#issuecomment-803784619)

**Comment by vitalykostak** [comment]
> @fbotalla May be this will [Help](https://github.com/HwangTaehyun/react-native-lottie-splash-screen/issues/4#issuecomment-803784619)

Yes. Thank you
