### ISSUE TITLE
Implementation with Kotlin

### ISSUE THREAD

**Issue by gaston-munoz** [HwangTaehyun/react-native-lottie-splash-screen#29]
Run `react-native info` in your project and share the content.

What `react-native-splash-screen` version are you using? v0.1.14

What platform does your issue occur on? (Android/iOS/Both) Android

Describe your issue as precisely as possible : 
  1) Steps to reproduce the issue or to explain in which case you get the issue
  2) Interesting `logs`

Join a screenshot or video of the problem on the simulator or device?

Show us the code you are using? 

I need to implement with Kotlin, I'm stuck, can you give us an example with Kotlin?

Thanks!

**Comment by HwangTaehyun** [comment]
Ah... I don't know well about Kotlin. Sorry for that
