### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by girish54321** [HwangTaehyun/react-native-lottie-splash-screen#3]
Run `react-native info` in your project and share the content.
`info Fetching system and libraries information...
(node:8224) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
    Memory: 2.67 GB / 7.70 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    Visual Studio: Not Found
  Languages:
    Java: 15.0.2
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

What `react-native-splash-screen` version are you using?
`"react-native-reanimated": "1.7.0"`
What platform does your issue occur on? (Android/iOS/Both)
Android

Describe your issue as precisely as possible : 
  1) Steps to reproduce the issue or to explain in which case you get the issue
  2) Interesting `logs`

**Thanks for the package its very cool but can you update the docs and one line "if you are using` react-native:0.62` or higher than no need to use `react-native link react-native-lottie-splash-screen`" after doing this my app was crashing for android.**

Join a screenshot or video of the problem on the simulator or device?

Show us the code you are using?

**Comment by HwangTaehyun** [comment]
It would be nice to add this guide in README.md. You can also modify the README.md and send a pull request. Thank you!

**Comment by girish54321** [comment]
@HwangTaehyun Sure will do 
Thank you for replying
