### ISSUE TITLE
Please explain Step 3 iOS -Swift.h file not found

### ISSUE THREAD

**Issue by vinayn-mend** [HwangTaehyun/react-native-lottie-splash-screen#30]
The project is always failing. Not able to configure successfully . -Swift.h file not found. @HwangTaehyun

**Comment by HwangTaehyun** [comment]
Hi @vinayn-mend Could you follow this?
https://github.com/HwangTaehyun/react-native-lottie-splash-screen/issues/4#:~:text=I%20think%20I,Thank%20you!
