### ISSUE TITLE
Error: No such module Lottie

### ISSUE THREAD

**Issue by GilTRipper** [HwangTaehyun/react-native-lottie-splash-screen#35]
Failing build cause of Xcode error
<img width="866" alt="Screenshot 2022-06-15 at 16 02 03" src="https://user-images.githubusercontent.com/73825055/173833329-eaf5eff4-a07f-4c84-b609-f3c2e318ebfc.png">

**Comment by girish54321** [comment]
@GilTRipper  Maybe this will https://github.com/HwangTaehyun/react-native-lottie-splash-screen/issues/4#issuecomment-803784619

**Comment by Aaqib925** [comment]
@GilTRipper 
Install npm package `lottie-react-native` and `cd ios && pod install`, once done, clean build folder from xcode and rebuild.
