### ISSUE TITLE
Animation taking time to load in iOS

### ISSUE THREAD

**Issue by harshmungara99** [HwangTaehyun/react-native-lottie-splash-screen#45]
I'm using **react-native-lottie-splash-screen (v1.0.1)**. In android it is loading instantly but in iOS it is taking delay of 2-3 seconds every-time. This issue is needs to be addressed as it's taking time to load animation in iOS. White screen is rendering every-time in iOS before animation took place.

**Comment by CoverID** [comment]
maybe you can find the answer here [https://stackoverflow.com/a/38265567](url)
for iOS **If you want to animate the launch screen then your need your launch storyboard scene or your launch image to be identical to your first view. You can then animate this first view**

**Comment by HwangTaehyun** [comment]
I hope this helps.
https://github.com/HwangTaehyun/react-native-lottie-splash-screen/issues/4
https://stackoverflow.com/questions/67434533/react-native-ios-splash-screen-using-lottie-file/68126111#68126111
