### ISSUE TITLE
Is bare workflow expo compatible?

### ISSUE THREAD

**Issue by igorcesarcode** [HwangTaehyun/react-native-lottie-splash-screen#51]
Is it possible to add in expo in a bare workflow project?

I am using expo sdk 46

**Comment by HwangTaehyun** [comment]
Sorry, I have I have no time for that. If someone develops and makes PR, I'll merge that.

**Comment by ansh** [comment]
@HwangTaehyun I'd be willing to pay for it! Let me know if you'd like to discuss further.

**Comment by HwangTaehyun** [comment]
@ansh @igorcesarcode I think he applied this package to expo bare flow. @cloudy-ninja Would you let me know some knowledge about that for others using expo bare flow? It's ok for some PR to README.md!

**Comment by HwangTaehyun** [comment]
@igorcesarcode @ansh I started to find some way to make this library compatible with the expo bare workflow w/ @cloudy-ninja. I will bring some good news soon.

**Comment by HwangTaehyun** [comment]
I managed to do this!! @ansh @igorcesarcode @cloudy-ninja Check and apply this to the expo bare workflow!
@clody-ninja I have no problem in release mode! The only issue I had is "main.jsbundle does not exist" issue. Could you heck again the expo bare workflow in README.md?
