### ISSUE TITLE
 Dynamic.Swift name is incorrect or #import "[PROJECT_NAME]-Swift.h"  file not found

### ISSUE THREAD

**Issue by umarabdulhuq** [HwangTaehyun/react-native-lottie-splash-screen#54]
I build the project successfully. after changing the extension of the Dynamic file.

 in the third step of plugin Configuration when creating a file Dynamic the extension must be '.swift' not '.Swift' 

<img width="1135" alt="Screenshot 2022-11-24 at 11 46 54 AM" src="https://user-images.githubusercontent.com/81737393/203713645-0bcaf22c-d22f-47fc-91fe-b808c1b6d9ec.png">

**Comment by girish54321** [comment]
Yes @umarabdulhuq  File name should be *Dynamic.swift* 
*.swift* You can fix the read me.md file and send Pull request to @HwangTaehyun

**Comment by HwangTaehyun** [comment]
I fixed it!
