### ISSUE TITLE
Retain animation background until .hide() is called in iOS

### ISSUE THREAD

**Issue by nicoflowerstore** [HwangTaehyun/react-native-lottie-splash-screen#57]
Is there a way to retain the animation's background until `hide()` is called in iOS? It works normally in Android but in iOS the animation rootview background goes away for some reason.

**Comment by madmeatballs** [comment]
@HwangTaehyun I'm using react-native cli for this project.

**Comment by HwangTaehyun** [comment]
@madmeatballs Thank you for your info!
