### ISSUE TITLE
how to change status bar black color

### ISSUE THREAD

**Issue by muhamedzeema** [HwangTaehyun/react-native-lottie-splash-screen#6]
Run `react-native info` in your project and share the content.

What `react-native-splash-screen` version are you using?
    "react-native-lottie-splash-screen": "^0.1.12",
What platform does your issue occur on? (Android/iOS/Both)
android
Describe your issue as precisely as possible : 
  1) Steps to reproduce the issue or to explain in which case you get the issue
  2) Interesting `logs`

Join a screenshot or video of the problem on the simulator or device?
<img width="294" alt="Screen Shot 2021-03-15 at 6 01 22 PM" src="https://user-images.githubusercontent.com/71822189/111184191-64b59d80-85b9-11eb-837f-54abe4b1ad74.png">
Show us the code you are using? 

i tried this solution [LINK](https://github.com/crazycodeboy/react-native-splash-screen/issues/95#issuecomment-453069591) but the app crashes when implementing this because i think you use SplashScreen.show(this, R.id.lottie);
so any help with this please ?
.

**Comment by girish54321** [comment]
@muhamedzeema you will have to do some changes in native android.

**Comment by muhamedzeema** [comment]
> @muhamedzeema you will have to do some changes in native android.

any assistance please ?

**Comment by girish54321** [comment]
add color.xml in ..android/app/src/main/res/values and pate following code

<?xml version="1.0" encoding="utf-8"?>
<resources>
    
    <color name="colorPrimary">#3F51B5</color>

    
    <color name="colorPrimaryDark">#A52D53</color>

    
    <color name="colorAccent">#FF4081</color>
</resources>

copy and pate following code in ..android/app/src/main/res/values/styles.xml

<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
   
   <item name="colorPrimary">@color/colorPrimary</item>
   <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
   <item name="colorAccent">@color/colorAccent</item>    
</style>

**Comment by muhamedzeema** [comment]
@girish54321 hello thanks for that, but already i had this implemented the issue is that the status bar is only Black on splash screen but the whole app have the color i set on colorPrimaryDark. my problem is that i can't change the black color from the splash screen, but the other app is fine. got me ?

**Comment by girish54321** [comment]
@muhamedzeema Ya I got you now but look only @HwangTaehyun can help you with this.

**Comment by muhamedzeema** [comment]
@girish54321 thank you!, @HwangTaehyun any help with this please ?

**Comment by HwangTaehyun** [comment]
Sorry for late. I check this issue. You should use this api `public static void show(final Activity activity, final int themeResId, final int lottieId)` to set theme color. Thank you!

**Comment by Kladislav** [comment]
@HwangTaehyun hi, how to configure the R.style.SplashTheme

**Comment by HwangTaehyun** [comment]
I followed the guide in https://github.com/crazycodeboy/react-native-splash-screen
> If you want to customize the color of the status bar when the splash screen is displayed:
> Create `android/app/src/main/res/values/colors.xml` and add
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="status_bar_color"><!-- Colour of your status bar here --></color>
</resources>
```

> Create a style definition for this in `android/app/src/main/res/values/styles.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="SplashScreenTheme" parent="SplashScreen_SplashTheme">
        <item name="colorPrimaryDark">@color/status_bar_color</item>
    </style>
</resources>
```

> Change your `show` method to include your custom style:
```java
SplashScreen.show(this, R.style.SplashScreenTheme);
```

My code is below. I applied red color status bar for example. 
You also can apply white or transparent status bar color.
Thank you!

* ### android/app/src/main/res/values/colors.xml
![image](https://user-images.githubusercontent.com/42465090/112585417-1ae07900-8e3d-11eb-91f4-476a998b9f7f.png)
* ### android/app/src/main/res/values/styles.xml
![image](https://user-images.githubusercontent.com/42465090/112585453-2c298580-8e3d-11eb-8fd3-c3288f866ec5.png)
* ### MainActivity.java
![image](https://user-images.githubusercontent.com/42465090/112585479-3a77a180-8e3d-11eb-8b3f-ea2dd0f003d9.png)
![image](https://user-images.githubusercontent.com/42465090/112585489-3d729200-8e3d-11eb-987e-494833082b7e.png)

**Comment by HwangTaehyun** [comment]
There's no problem with this issue anymore. I will close the issue.

**Comment by ghazihussain** [comment]
how to change status bar in ios?

**Comment by girish54321** [comment]
Changes Safeareaview color? maybe @ghazihussain
