### ISSUE TITLE
[your-project-name]-Swift.h file not found

### ISSUE THREAD

**Issue by aidshon** [HwangTaehyun/react-native-lottie-splash-screen#62]
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.15.0
    Yarn: Not Found
    npm: 8.5.5
    Watchman: 2022.03.21.00
  Managers:
    CocoaPods: 1.11.3
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.0.1/14A400 
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

"react-native-lottie-splash-screen": "^1.0.1"

What platform does your issue occur on? (Android/iOS/Both)
I only tried on iOS

The issue:
I followed the instructions and did all the steps but I cannot move forward because xCode keeps saying [your-project-name]-Swift.h file not found . Why is that happening?

**Comment by HwangTaehyun** [comment]
@aidshon Hi! Could you see this issue? https://github.com/HwangTaehyun/react-native-lottie-splash-screen/issues/4#:~:text=Hi%20%40KawaljeetCuelogic%20when,repo%20for%20iOS

**Comment by HwangTaehyun** [comment]
I will close this issue!
