### ISSUE TITLE
How to configure UIView for Lottie Splash on AppDelegate.mm RN v0.71

### ISSUE THREAD

**Issue by codeOlam** [HwangTaehyun/react-native-lottie-splash-screen#63]
RN v0.71
react-native-splash-screen: v1.0.1
Platform: IOS

@HwangTaehyun please can you help guide me on how to configure RNSplashScreen on AppDelegate.mm for ios?

**Comment by GoktuqCan** [comment]
I'm having issues too. Splash screen doesn't seem to be mounted at all. It was working perfectly before RN 0.71 update.

**Comment by codeOlam** [comment]
Yes. I have been using it for me recent applications before v0.71, I tried looking for a work around. I couldn't get it to work yet.

**Comment by HwangTaehyun** [comment]
rootview is gone to the [RCTAppDelegate.mm](https://github.com/facebook/react-native/pull/34384/files#diff-155a2899331c482b4dffb694f445e7f6770d4a56501e3895bfbbcb514e78b5a0)

We should find some way to get rootview from the super class RCTAppDelegate of AppDelegate! @codeOlam @GoktuqCan

**Comment by codeOlam** [comment]
Thank you @HwangTaehyun. I will look toward this direction

**Comment by madmeatballs** [comment]
can we access it after `return [super application:application didFinishLaunchingWithOptions:launchOptions];` ?

Currently, trying how we can make this work. Really need this for our project lol.

**Comment by ElSeniorMikael** [comment]
> 

Thanks @madmeatballs your solution worked for me, we just need to be sure that is the LAST action inside of =>
`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`

Good job for your solution and thanks again

**Comment by HwangTaehyun** [comment]
@madmeatballs Thank you for your hard work! If possible, could you make some PR to rn v0.71?

**Comment by codeOlam** [comment]
Super Awesome @madmeatballs, thank you. I just got back to my project and tried out your solution here. worked great for me, only that i have to comment out `self.initialProps = @{};`, remember my version is `RNv0.71`.

Thank you for taking out time to do this @madmeatballs

**Comment by madmeatballs** [comment]
> @madmeatballs Thank you for your hard work! If possible, could you make some PR to rn v0.71?

Sure, will make a PR. 👍 Glad this helped.
