### ISSUE TITLE
[IOS] Disable animation loop 

### ISSUE THREAD

**Issue by Kladislav** [HwangTaehyun/react-native-lottie-splash-screen#7]
Exists for android  `lottie_loop` prop, how can i disable it for ios?

**Comment by Kladislav** [comment]
loop disabled by default on ios

**Comment by TheOmran** [comment]
What about enabling loop? :)

**Comment by hungnq139** [comment]
@TheOmran : in Dynamic.swift replace play function with 

`@objc func play(animationView: AnimationView) {
    animationView.play(fromProgress: 0.0, toProgress: 1.0, loopMode: LottieLoopMode.loop, completion: { (success) in
          RNSplashScreen.setAnimationFinished(true)
        }
    );
  }`

**Comment by vfa-locltb** [comment]
> What about enabling loop? :)

Same question, can anyone help?

**Comment by hungnq139** [comment]
> @TheOmran : in Dynamic.swift replace play function with
> 
> `@objc func play(animationView: AnimationView) { animationView.play(fromProgress: 0.0, toProgress: 1.0, loopMode: LottieLoopMode.loop, completion: { (success) in RNSplashScreen.setAnimationFinished(true) } ); }`

@vfa-locltb it doesn't work ?

**Comment by vfa-locltb** [comment]
> > @TheOmran : in Dynamic.swift replace play function with
> > `@objc func play(animationView: AnimationView) { animationView.play(fromProgress: 0.0, toProgress: 1.0, loopMode: LottieLoopMode.loop, completion: { (success) in RNSplashScreen.setAnimationFinished(true) } ); }`
> 
> @vfa-locltb it doesn't work ?

Sorry, I thought this was an android thread, I got it figured out now.
