### ISSUE TITLE
Lottie Spash Screen cannot build code on Android (RN-0.71.1)

### ISSUE THREAD

**Issue by elsieej** [HwangTaehyun/react-native-lottie-splash-screen#70]
Run `react-native info` in your project and share the content.
info Fetching system and libraries information...
System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 956.56 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: Not Found
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: 2022.12.26.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/elsie/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 10.1.3 => 10.1.3 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.2 is now available (your project is running on v0.71.1).

What `react-native-splash-screen` version are you using?
  "react-native-lottie-splash-screen": "^1.1.1",

What platform does your issue occur on? (Android/iOS/Both) Android

Describe your issue as precisely as possible : 
  1) Steps to reproduce the issue or to explain in which case you get the issue
   Following the README configuration, i success on IOS, but on Android doesn't when i build code.
  2) Interesting `logs`
  This logs say:
 `Execution failed for task ':react-native-lottie-splash-screen:processDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.facebook.react:react-android:0.71.1] /Users/elsie/.gradle/caches/transforms-3/470a2d1ee578c374e7b91032ed5c766b/transformed/jetified-react-android-0.71.1-debug/AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)`

So i guess, the minSDK version of our lib is outdated from ReactNative 0.71.1, so please update it.

**Comment by L-Weisz** [comment]
i have the same issue

**Comment by SerSerch** [comment]
I use this version and it is work
"react": "18.1.0",
"react-native": "0.70.2",

**Comment by Bibazavr** [comment]
#76 create PR for fix it

**Comment by HwangTaehyun** [comment]
@Bibazavr Sorry for being late. Thank you for your contribution! I published 1.1.2 which includes this fix.
