### ISSUE TITLE
how to change status bar black color (IOS)

### ISSUE THREAD

**Issue by ghazihussain** [HwangTaehyun/react-native-lottie-splash-screen#8]
Run `react-native info` in your project and share the content.

What `react-native-splash-screen` version are you using?

What platform does your issue occur on? (Android/iOS/Both)

Describe your issue as precisely as possible : 
  1) Steps to reproduce the issue or to explain in which case you get the issue
  2) Interesting `logs`

Join a screenshot or video of the problem on the simulator or device?

Show us the code you are using?

**Comment by HwangTaehyun** [comment]
Hi, I hope this helps.
[https://stackoverflow.com/questions/53939953/how-to-set-launch-screen-status-bar-color-to-white](https://stackoverflow.com/questions/53939953/how-to-set-launch-screen-status-bar-color-to-white)

**Comment by HwangTaehyun** [comment]
I close the issue
