### ISSUE TITLE
In my case the Lottie splash screen is not integrated it have error.

### ISSUE THREAD

**Issue by mehranali12** [HwangTaehyun/react-native-lottie-splash-screen#83]
"react-native-lottie-splash-screen": "^1.1.2",

platform (Android)

![new error](https://github.com/HwangTaehyun/react-native-lottie-splash-screen/assets/81305073/c351da8e-bab3-4085-911c-44ef5defd32b)

Join a screenshot or video of the problem on the simulator or device?

this is the **_launch_screen.xml_** file.
_**<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              xmlns:tools="http://schemas.android.com/tools"
              tools:context=".MainActivity"
              android:orientation="vertical"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:background="@drawable/launch_screen"
>
    <com.airbnb.lottie.LottieAnimationView
            android:id="@+id/lottie"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:lottie_rawRes="@raw/loading"
            app:lottie_autoPlay="true"
            app:lottie_loop="false"
    />
</LinearLayout>**_

this is the error message in text.
_*** What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
   > Resource compilation failed (Failed to compile resource file: D:\Apps\ReactNative\HisabKitab\android\app\src\main\res\layout\launch_screen.xml: . Cause: com.ctc.wstx.exc.WstxParsingException: Illegal processing instruction target ("xml"); xml (case insensitive) is reserved by the specs.
      at [row,col {unknown-source}]: [31,5]). Check logs for more details.**_

**Comment by HwangTaehyun** [comment]
I don't think the problem lies with this library.
You can refer to this https://stackoverflow.com/questions/23359572/android-studio-execution-failed-for-task-appmergedebugresources-if-projec

**Comment by HwangTaehyun** [comment]
I will close the issue.
