### ISSUE TITLE
How can we use this with Expo

### ISSUE THREAD

**Issue by segun-flexible** [HwangTaehyun/react-native-lottie-splash-screen#85]
Please am using expo, how can I incorporate this with Expo latest version

**Comment by HwangTaehyun** [comment]
Please refer this https://github.com/HwangTaehyun/react-native-lottie-splash-screen?tab=readme-ov-file#expo-bare-workflow

I don't use expo now, so I don't know how I can incorporate the latest expo. Sorry about that.
So you can use this compatible expo version in README.md

**Comment by HwangTaehyun** [comment]
I will close this issue.
