### ISSUE TITLE
Splash screen gets skipped on production mode only! [ios]

### ISSUE THREAD

**Issue by mayfairr** [HwangTaehyun/react-native-lottie-splash-screen#9]
Hey, I have copied the code in the documentation exactly. The App works perfectly in Debug mode, but when I switch to production mode the splash screen is just skipped and goes straight to the application. I can see it for maybe 1/2 a second. Is this a known bug?

**Comment by mayfairr** [comment]
Alright, after a long 7 hours on this project. I realized that the `expo-splash-screen` package was conflicting with my project so by cross-referenced @girish54321 fork I realized my AppDelegate.h included this: 
```
#ifdef DEBUG
   
#else
    EXUpdatesAppController *controller = [EXUpdatesAppController sharedInstance];
    controller.delegate = self;
    [controller startAndShowLaunchScreen:self.window];
#endif

```

Which only ran in the release version. Again my thanks to you @girish54321 🎉🎉
 
I will close the issue now.

**Comment by cloudy-ninja** [comment]
Hi @mayfairr The same issue is happening in my project as well, but I couldn't find the codes you mentioned in my AppDelegate.h file. Here are the codes.

`#import <Foundation/Foundation.h>
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>

#import <Expo/Expo.h>

@interface AppDelegate : EXAppDelegateWrapper <RCTBridgeDelegate>

@end
`

**Comment by cloudy-ninja** [comment]
Could you help me? I am not sure what I should change in this case.
Thank you for your help
