### ISSUE TITLE
How to remove ic_launcher.png that appears before the animated splash?

### ISSUE THREAD

**Issue by Digital-Human-BK** [HwangTaehyun/react-native-lottie-splash-screen#94]
React Native newbie here. So far no issues with the library itself. I need some advice on removing the app icon before the animated splash on Android. In the example .gif you can see the app starts straight with the splash. 

![Lottie-Splash-Screen-Android](https://github.com/HwangTaehyun/react-native-lottie-splash-screen/assets/85568905/1a0c4692-5266-4dc2-b463-305c8991b875)

Also, I would be very grateful if someone could tell me how to make the navigation and status bar white during the splash animation.

**Comment by HwangTaehyun** [comment]
@Digital-Human-BK I don't understand and see any logo before the splash screen in your question.
In the case of iOS, Could you look at this issue? https://github.com/HwangTaehyun/react-native-lottie-splash-screen/issues/4#issuecomment-803745045

I've shared below my answer to the same issue about the status bar for you to look at.
https://github.com/HwangTaehyun/react-native-lottie-splash-screen/issues/6.
