### ISSUE TITLE
The iOS build fails even after completing all steps, showing "11 duplicate symbols" and "Linker command failed with exit code 1 (use -v to see invocation)"

### ISSUE THREAD

**Issue by omarsaade** [HwangTaehyun/react-native-lottie-splash-screen#96]
info Fetching system and libraries information...
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 432.77 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 3.6.4 - ~/.nvm/versions/node/v20.13.1/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.3 AI-233.14808.21.2331.11842104
    Xcode: 15.4/15F31d - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**What `react-native-splash-screen` version are you using?**

    **"lottie-ios": "3.2.3",
    "react-native-lottie-splash-screen": "^1.1.2",**
   

What platform does your issue occur on? (Android/iOS/Both)

**IOS**

Describe your issue as precisely as possible : 

The iOS build fails even after completing all steps, showing "**11 duplicate symbols**" and "**Linker command failed with exit code 1 (use -v to see invocation**)"

**Comment by omarsaade** [comment]
> **IOS**
> 
> Describe your issue as precisely as possible :
> 
> The iOS build fails even after completing all steps, showing "**11 duplicate symbols**" and "**Linker command failed with exit code 1 (use -v to see invocation**)"

**Comment by rahulkumar-ios** [comment]
what is the work around for this issue @omarsaade. can you please let me know it will be very helpfull.
